export default [
    "Built with Mantine!",
    "loading screen tips be like:",
    "have you guys heard about rust its 🚀🚀🚀 BLAZINGLY FAST 🚀🚀🚀 and 🚀🚀🚀 MEMORY SAFE 🚀🚀🚀",
    "subscribe to technoblade",
    "the waffle house has found its new host",
    '"You can\'t just shoot a hole into the surface of mars"',
    "I used to rule the world",
    "world.execute(me);",
    "sus",
    "I love May very much",
    '"If the laws of physics no longer apply in the future, God help you."',
    "me when i need to code javascript: and then she sacrificed HER SANITY!!!",
    "This is the LockPickingLawyer and today...",
    "It's quite simple, actually.",
    "youre a kid now, youre a squid now",
    "流れてく 時の中ででも 気だるさが ほらグルグル廻って",
    "STANDING HERE, I REALIZE",
    "My favorite youtuber is still Technoblade",
    "my brain's specs are as good as my laptop's - potato",
    "i animated lagtrain using minecraft maps once",
    "The Oldest Anarchy Server in Minecraft",
    "TRANS RIGHTS!",
    "Technoblade never dies.",
    "Reach for the Summit",
    "I love Alan Becker's animations tbh",
    "- Removed Herobrine",
    "the animatronics do get a bit quirky at night",
    "Hello its Josh welcome back to LetsGameItOut",
    "oh hey look funny characters: dQw4w9WgXcQ",
    "I generally dont *think* so therefore i dont think I *am* either?",
    "en passant???? new response just dropped??? actual zombie??",
    "XNOR XNOR XNOR",
    "Hey! Vsauce - Michael here. Your home security is great. Or is it?",
    "Is your refridgerator running?",
    '"I am at /.*/"   - Tom Scott',
    "I selled my wife for internet connection (jk no i love you may)",
    "Hello internet, welcome to Game Theory!",
    "This was a triumph",
    "🥚 <- easter egg",
    "(they were roommates)",
    "theres probably a lot more projects im forgetting to put here lmao",
];
